---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/figures_Table_Table2/figures_Table_Table2.xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/3/articles/399889/master/file/figures/figures_Table_Table2/figures_Table_Table2.xlsx"
    folder_url: "/users/3/articles/399889/master/folder/figures/figures_Table_Table2"
